### ISSUE TITLE
The login box is transparent for no reason.

### ISSUE THREAD

**Issue by benrobson** [VectorMC/Issues#11]
https://gyazo.com/387d51636950b1599632fde1c57653e9

**Comment by alexanderjoe** [comment]
Its meant to be transparent so you can see the particles behind it.

**Comment by benrobson** [comment]
The particles shouldn't be the main show of these pages. 
The content inside of the boxes should be.
The particles are only there for show and not for anything else.

**Comment by jasoryeh** [comment]
Untransparencied it
