### ISSUE TITLE
Reformat registration confirmation email template.

### ISSUE THREAD

**Issue by benrobson** [VectorMC/Issues#12]
- The logo in the header of the email is still the old Pagoda Network logo.
- The bottom right link "Issues" links to the old issues page (https://github.com/PagodaNetwork/Issues/issues)
- The overall formatting needs to be touched up, make it look nice, doesn't look very good.
- Administration is spelt wrong at the bottom of the email "The VectorMC Aministration and Staff team"

![image](https://user-images.githubusercontent.com/15405528/43056393-7365fbec-8e7f-11e8-9206-1df75893d483.png)

**Comment by alexanderjoe** [comment]
Let Input setup stuff, stuff gets weird.

**Comment by alexanderjoe** [comment]
Should be fixed, re-open if not.
