### ISSUE TITLE
Lobby has a day/night cycle, when it really shouldn't

### ISSUE THREAD

**Issue by benrobson** [VectorMC/Issues#19]
https://gyazo.com/f8d8da342d9e177ed209c82d396460bd

**Comment by jasoryeh** [comment]
I intentionally left it cycling

**Comment by benrobson** [comment]
I don't like the idea of it intentionally cycling. The issue is with those users who don't have a very good computer screen or some other brightness issue, when they enter the lobby you won't be able to see a thing.

**Comment by jasoryeh** [comment]
its already fixed lol
