### ISSUE TITLE
Allows users to edit/delete post comments that they are the author of.

### ISSUE THREAD

**Issue by benrobson** [VectorMC/Issues#31]

**Comment by alexanderjoe** [comment]
Solved.
![a50336f983defc6d157e6713a1c051de](https://user-images.githubusercontent.com/8846229/61035079-7d0cf800-a394-11e9-8e47-3bfb98dbfd6b.png)
![a586b05a7a4d3076fad7a1d589f0ecf3](https://user-images.githubusercontent.com/8846229/61035082-7ed6bb80-a394-11e9-957b-50fc56a5d06b.png)
