### ISSUE TITLE
Forgot password page

### ISSUE THREAD

**Issue by ghost** [VectorMC/Issues#44]
The forgot password script don't work when you put the email. I get the success message but it doesn't work because i don't recive any email, i've checked the spam box too and nothing.

**Comment by jasoryeh** [comment]
Try waiting a few minutes

**Comment by jasoryeh** [comment]
If you still didn't get it, DM me on Discord, I'll give you it.

**Comment by alexanderjoe** [comment]
Fixed and tested it myself.

**Comment by ghost** [comment]
kk, thanks
