### ISSUE TITLE
Sidebar menu on forums needs to be a bit more cleaner.

### ISSUE THREAD

**Issue by benrobson** [VectorMC/Issues#46]
![image](https://user-images.githubusercontent.com/15405528/44319775-4b8bf500-a481-11e8-97d6-e7cac54b9608.png)

**Comment by jasoryeh** [comment]
It used to be fixed on the old site, but I guess I didn't really make the layout on this new site.

**Comment by jasoryeh** [comment]
cleaned up on production and staging.
