### ISSUE TITLE
Middle section of the homepage, the overview div class size is unreasonably big.

### ISSUE THREAD

**Issue by benrobson** [VectorMC/Issues#5]
https://gyazo.com/d3407f0ff27383e14146e317cf226c6a

height: 74vh is alot better.

**Comment by alexanderjoe** [comment]
I shrunk it to 64vh, which made it even more condensed but looks the same.

**Comment by benrobson** [comment]
This issue has reappeared.

**Comment by jasoryeh** [comment]
64 is too small text overflows to next div, increased to 75

**Comment by jasoryeh** [comment]
Unless someone can make a smaller, but yet good summary, we shall keep it 75
