### ISSUE TITLE
Fix this little thing, it annoys me

### ISSUE THREAD

**Issue by benrobson** [VectorMC/Issues#53]
I can't find where it is.
https://gyazo.com/270f55a034a836b9a39b81b5a5cb616e

**Comment by jasoryeh** [comment]
Fixed
![image](https://user-images.githubusercontent.com/13290941/45463341-97b50880-b6c0-11e8-89f3-53f6f9bb02c5.png)
![image](https://user-images.githubusercontent.com/13290941/45463348-9daae980-b6c0-11e8-8397-e47b907c6bcf.png)
![image](https://user-images.githubusercontent.com/13290941/45463358-a996ab80-b6c0-11e8-9ec0-8eb5522dca8b.png)

**Comment by jasoryeh** [comment]
Will show when staging is pushed to main
