### ISSUE TITLE
The Retired rank colour isn't the correct color.

### ISSUE THREAD

**Issue by benrobson** [VectorMC/Issues#57]
https://gyazo.com/d49e0039a6925cb9724f2af0d3740a41

**Comment by jasoryeh** [comment]
This isn't an actual issue, the retired rank's color is correct, however if you are referring to the user's name color, the color is also correct, the colors of the other ranks are actually incorrect as they add a blue/aqua chatcolor in it's prefixes.

**Comment by jasoryeh** [comment]
A fix was applied to all ranks that removed this trailing chat color
