### ISSUE TITLE
Homepage shop link.

### ISSUE THREAD

**Issue by benrobson** [VectorMC/Issues#6]
https://gyazo.com/e7c25d32293266bc2d08efd42fd1f686

Instead of setting the link to #soon, display an alert saying 
`alert("The shop is currently not in operation, will be coming #soon")`

**Comment by jasoryeh** [comment]
![image](https://user-images.githubusercontent.com/13290941/43032520-83acf3fc-8c6d-11e8-8e36-40d4f45636ba.png)
