### ISSUE TITLE
I get credits for kill assists when I'm not even playing

### ISSUE THREAD

**Issue by Riilo** [VectorMC/Issues#66]
![issue5](https://user-images.githubusercontent.com/30203017/61168322-cf663880-a58f-11e9-91f6-954d523b4274.PNG)
I'm receiving assist xp and I haven't even done /join.

**Comment by Riilo** [comment]
I can be afk and two people can be constantly fighting and I'm just receiving credits automatically

**Comment by jasoryeh** [comment]
Fixed as of https://github.com/VectorMC/AvicusNetwork/commit/9403755fa8a86f6549656e05c84744850d682d6f

**Comment by jasoryeh** [comment]
at least.. it should be.
