### ISSUE TITLE
On the rules page, old issue link is hyperlinked.

### ISSUE THREAD

**Issue by benrobson** [VectorMC/Issues#7]
https://gyazo.com/1bac64c6e4651ab7875a238df987c924

"The website is not yet completed! Please report errors on our GitHub page." links to https://github.com/PagodaNetwork/Issues/issues instead of https://github.com/VectorMC/Issues/issues

**Comment by alexanderjoe** [comment]
This was actually most of the website if you find a place that wasn't updated lmk.
