### ISSUE TITLE
The shop link in the navigation bar directs to the old shop buycraft.

### ISSUE THREAD

**Issue by benrobson** [VectorMC/Issues#9]
https://gyazo.com/8a0199e092325accab2492f3d6278a4e

Directs to https://pagoda.buycraft.net

**Comment by jasoryeh** [comment]
![image](https://user-images.githubusercontent.com/13290941/43032521-915f452c-8c6d-11e8-9fbd-c04094f1ddc1.png)

Will close when we have shop.

**Comment by alexanderjoe** [comment]
Fixed.
